import { Breadcrumb } from '../components/Breadcrumb';

const tables = {
  Men: [['S', '91–96', '42–44', '68–70'], ['M', '96–101', '44–46', '70–72'], ['L', '101–106', '46–48', '72–74'], ['XL', '106–111', '48–50', '74–76'], ['XXL', '111–116', '50–52', '76–78']],
  Women: [['XS', '76–81', '34–36', '56–58'], ['S', '81–86', '36–38', '58–60'], ['M', '86–91', '38–40', '60–62'], ['L', '91–96', '40–42', '62–64'], ['XL', '96–101', '42–44', '64–66']],
  Unisex: [['S', '91–96', '42–44', '68–70'], ['M', '96–101', '44–46', '70–72'], ['L', '101–106', '46–48', '72–74'], ['XL', '106–111', '48–50', '74–76'], ['XXL', '111–116', '50–52', '76–78']],
};

function SizeTable({ title, rows }) {
  return <div className="overflow-x-auto rounded-2xl border border-gray-200"><table className="min-w-[520px] w-full text-left text-sm"><caption className="border-b border-gray-200 bg-section px-5 py-4 text-left font-semibold uppercase tracking-[0.2em]">{title} tops · measurements in cm</caption><thead><tr className="border-b border-gray-200 text-xs uppercase tracking-[0.15em] text-secondary"><th className="px-5 py-3">Size</th><th className="px-5 py-3">Chest</th><th className="px-5 py-3">Shoulder</th><th className="px-5 py-3">Length</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]} className="border-b border-gray-100 last:border-0"><td className="px-5 py-3 font-semibold">{row[0]}</td><td className="px-5 py-3 text-secondary">{row[1]}</td><td className="px-5 py-3 text-secondary">{row[2]}</td><td className="px-5 py-3 text-secondary">{row[3]}</td></tr>)}</tbody></table></div>;
}

export function SizeGuide() {
  return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16"><Breadcrumb items={[{ label: 'Home', to: '/' }, { label: 'Size Guide' }]} /><section className="mb-14 max-w-3xl"><p className="mb-4 text-xs font-semibold uppercase tracking-[0.35em] text-secondary">Fit notes</p><h1 className="text-4xl font-heading font-semibold uppercase tracking-tight md:text-6xl">Find your fit</h1><p className="mt-5 text-secondary">This is a general size guide. Product-specific measurements are not currently stored in MongoDB, so check each product page for available sizes and fit notes.</p></section><div className="grid gap-6 lg:grid-cols-3">{Object.entries(tables).map(([title, rows]) => <SizeTable key={title} title={title} rows={rows} />)}</div><section className="mt-16 grid gap-8 border-t border-gray-200 pt-12 md:grid-cols-2"><div><h2 className="text-2xl font-heading font-semibold">How to measure</h2><p className="mt-3 text-sm leading-7 text-secondary">Use a soft tape and keep it level without pulling tight.</p></div><dl className="grid grid-cols-2 gap-6 text-sm"><div><dt className="font-semibold uppercase tracking-[0.15em]">Chest</dt><dd className="mt-2 text-secondary">Around the fullest point.</dd></div><div><dt className="font-semibold uppercase tracking-[0.15em]">Waist</dt><dd className="mt-2 text-secondary">Around your natural waist.</dd></div><div><dt className="font-semibold uppercase tracking-[0.15em]">Hips</dt><dd className="mt-2 text-secondary">Around the fullest point.</dd></div><div><dt className="font-semibold uppercase tracking-[0.15em]">Inseam</dt><dd className="mt-2 text-secondary">From inner leg to ankle.</dd></div></dl></section></div>;
}
